version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: node_container
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/dealershipsDB

volumes:
  mongo_data: